### ISSUE TITLE
1.1.0 update fails to install via Nuget

### ISSUE THREAD

**Issue by murraybiscuit** [paranoidTwitch/Reckdl#1]
I'm getting this error on the latest update in VS PM console:

> Could not install package 'Reckdl 1.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

The previous version of Reckdl worked fine for me. It appears that github master isn't up to date with 1.1.0, so I can't really see what's going on.

**Comment by paranoidTwitch** [comment]
I left out the package info for 4.5.1. Sorry about that, didn't think anyone else was using it. I'll try to fix that tonight or tomorrow and get source control updated. You should still be able to use the old version the only thing that was fixed in the update was how its handling csv calls.

**Comment by paranoidTwitch** [comment]
Alright I have updated the source control and pushed a new package into nuget.org. I set it back to the original .net version it was built with. I'll deal with updating the .net version in the future. Let me know if that solves your issue, if not we can put our heads together and figure it out. Sorry again for the headache!

**Comment by murraybiscuit** [comment]
Hmm. I've installed build tools for .net 4-4.6, 4.6.1, 4.6.2, 4.7... The latest version from this is the only build fail I'm getting. I've rolled back to 1.0.1 for now and pinned it there in packages.conf

**Comment by paranoidTwitch** [comment]
This lib will be updated to .net standard 2.0 in the near future. If you experience further install issues after the update please open a new ticket for it. Hopefully now that net core has settled down a bit things wont break quite as much between updates.
